version: '3.7'
services:

  # Environment
  bank-db:
    image: postgres
    hostname: bank-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
